config/routes.rb
Rails.application.routes.draw do

  # Homepage
  root 'welcome#home'

  # Devise
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # Nested Resources - users/projects
  resources :users, only: [:show] do
    resources :projects do
      resources :project_tasks
    end
  end

  # Task
  resources :tasks

  # Scope
  get '/project_tasks/recent', to: 'project_tasks#recent'

  get '/users/:id/project_tasks', to: 'project_tasks#user_project_tasks', as: :user_project_tasks

end

app/models/task.rb
class Task < ApplicationRecord
  # Associations
  has_many :projects_tasks, dependent: :destroy
  has_many :projects, through: :projects_tasks
  # has_many :users, through: :projects_tasks
  # Validations
  validates :name, presence: true

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # Helpers
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  def index
    @tasks = Task.all
  end


  def new
    @task = Task.new
    @user = current_user
  end

  def create
    @task = current_user.tasks.new(task_params)

    if @task.save
      redirect_to task_path, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update

    if @task.update(task_params)
      redirect_to @task, notice: 'Team was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user = current_user
    @project = Project.find_by(id: params[:project_id])
    @task.destroy
    redirect_to project_path(@user, @project), notice: 'Task was successfully destroyed.'
  end

  private # This encapsulates these methods

  # Strong params
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:name, :description)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for :task do |f| %>
    <strong><%= f.label :name %></strong>
    <%= f.text_field :name, class:"form-control" %><br>
    <strong><%= f.label :description %></strong>
    <%= f.text_area :description, class:"form-control" %><br>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/tasks/edit.html.erb
<% content_for :header do %>
  <h1>Edit Task</h1>
<% end %>

<% content_for :content do %>
  <% if @task.errors.any? %>
    <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
    </ul>
  <% end %>
  <%= render partial: "form", locals: {task: @task } %>
<% end %>

app/views/tasks/index.html.erb
<% content_for :header do %>
  <h1><%= @user.email %> </h1>
  <h3>Tasks:</h3>
<% end %>

<% content_for :content do %>
  <% if !@tasks.any? %>
    <p><%= link_to "Create Task", new_task_path(@user), class: 'btn btn-primary'  %></p>
  <% else %>
    <% @tasks.each do |task| %>
      <div class="card border-info mb-3">
        <div class="card-body">
          Name:<h5 class="card-title"><%= link_to task.name, project_path(task), class: 'btn btn-primary'  %></h5>
          Description:<p class="card-text"><%= task.description, class: 'btn btn-primary'  %></p>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/tasks/new.html.erb
<% content_for :header do %>
  <h1>Create a New Task</h1>
<% end %>

<% content_for :content do %>
    <% if @task.errors.any? %>
    <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
    </ul>
  <% end %>
  <%= render partial: "form", locals: {task: @task} %>
<% end %>

app/views/tasks/show.html.erb
<% content_for :header do %>
  <h1><%= @task.name %></h1>
  <p><em><%= @task.description %></em></p>
<% end %>

<% content_for :content do %>
  <%= link_to 'Add Task', new_task_path(@task), class: 'btn btn-primary'  %>
  <%= link_to 'Edit Task', edit_task_path(@task), class: 'btn btn-primary'  %>
  <%= link_to 'Create New Project', new_project_path, class: 'btn btn-primary'  %>
  <%= link_to 'Back', :back, class: 'btn btn-primary'  %>
<% end %>