config/routes.rb
Rails.application.routes.draw do

  # Homepage
  root 'welcome#home'

  # Devise
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # Nested Resources - users/projects
  resources :users, only: [:show] do
    resources :projects do
      resources :project_tasks
    end
  end

  # Task
  resources :tasks

  # Scope
  get '/project_tasks/recent', to: 'project_tasks#recent'

  get '/users/:id/project_tasks', to: 'project_tasks#user_project_tasks', as: :user_project_tasks

end

app/models/project_task.rb
class ProjectTask < ApplicationRecord
  # Associations
  belongs_to :user
  belongs_to :task
  belongs_to :project
  # Validations
  validates :name, :due_date, presence: true
  # Attributes
  accepts_nested_attributes_for :task, :project
  # Scope
  scope :recent, -> { order(created_at: :desc) }
  scope :due_soon, -> { order(due_date: :asc) }
  scope :done, -> { where(done?: :true ) }


end

app/controllers/project_tasks_controller.rb
class ProjectTasksController < ApplicationController
  # Helpers
  before_action :set_project_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  def index
    @project_tasks = ProjectTask.all
    @user = current_user
    @project = Project.find_by(id: params[:project_id])
  end

  def new
    @project_task = ProjectTask.new
    @project = Project.find_by(id: params[:project_id])
    @task = @project_task.build_task
    @user = current_user
  end

  def create
    @project_task = ProjectTask.new(project_task_params)
    @user = current_user
    @project = Project.find_by(id: params[:project_id])
    if @project_task.save
      redirect_to user_project_project_tasks_path(@user, @project, @project_task), notice: 'Project Task was successfully created.'
    else
      render :new
    end
  end

  def show
    @user = current_user
    @project = Project.find_by(id: params[:project_id])
  end

  def edit
    @user = current_user
    @project = Project.find_by(id: params[:project_id])
  end

  def update
    @user = current_user
    @project = Project.find_by(id: params[:project_id])
    if @project_task.update(project_task_params)
      redirect_to user_project_project_task_path(@user, @project, @project_task), notice: 'Project Task was successfully updated.'
   else
      render :edit
   end
  end

  def destroy
    @user = current_user
    @project = Project.find_by(id: params[:project_id])
    @project_task.destroy
    redirect_to user_projects_path(@user, @project), notice: 'Project Task was successfully destroyed.'
  end

  def recent
    @recent = ProjectTask.recent
  end

  def user_project_tasks
    @user = User.find_by(id: params[:id])
    @project_tasks = @user.project_tasks
  end

  private # This encapsulates these methods

  # Strong params
    def set_project_task
      @project_task = ProjectTask.find_by(id: params[:id])
    end

    def project_task_params
      params.require(:project_task).permit(:id, :name, :description, :due_date, :user_id, :project_id, user_attributes: [:id, :email ], task_attributes: [:id, :name, :description, :users], project_attributes: [:id, :name ] )
    end
end

app/views/project_tasks/_form.html.erb
    <div class='form-group'>
      <%= f.hidden_field :user_id, :value => @user.id %>
      <%= f.hidden_field :project_id, :value => @project.id %>
      <strong><%= f.label :name %></strong>
      <%= f.text_field :name, class:"form-control" %><br>
      <strong><%= f.label :description %></strong>
      <%= f.text_area :description, class:"form-control" %><br>
      <strong><%= f.label :due_date %></strong>
      <%= f.date_field :due_date, class:"form-control" %><br>

    </div >
    <div class='form-group'>
      <%= f.fields_for :task do |t| %>
          <strong><%= t.label "Task Name:" %></strong>
        <%= t.text_field :name, class:"form-control" %><br>
        <strong><%= t.label "Task Description:" %></strong>
        <%= t.text_area :description, class:"form-control" %><br>
    </div>


  <%= f.submit class: "btn btn-primary" %>

  <% end %>

app/views/project_tasks/edit.html.erb
<% content_for :header do %>
  <h1>Edit Project Task</h1>
<% end %>

<% content_for :content do %>
    <% if @project_task.errors.any? %>
    <ul>
        <% @project_task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
    </ul>
  <% end %>

  <%= form_for [@user, @project, @project_task] do |f| %>
    <div class='form-group'>
          <strong><%= f.label :name %></strong>
          <%= f.text_field :name, class:"form-control" %><br>
          <strong><%= f.label :description %></strong>
          <%= f.text_area :description, class:"form-control" %><br>
          <strong><%= f.label :due_date %></strong>
          <%= f.date_field :due_date, class:"form-control" %><br>
    </div >
        <div class='form-group'>
          <%= f.fields_for :task do |t| %>
              <strong><%= t.label "Task Name:" %></strong>
            <%= t.text_field :name, class:"form-control" %><br>
            <strong><%= t.label "Task Description:" %></strong>
            <%= t.text_area :description, class:"form-control" %><br>
        </div>

    <%= f.submit class: "btn btn-primary", method: :update %>
<%end %>
    <% end %>
  <% end %>

app/views/project_tasks/index.html.erb
<% content_for :header do %>
    <div class="container text-center">
        <h1>Project Tasks:</h1>
    </div>
<% end %>

<% content_for :content do %>
    <div class="container text-center mb-3">
        <%= link_to "Create New Task", new_user_project_project_task_path(@user, @project, @project_task), class: 'btn btn-primary'  %>
            <% @project_tasks.each do |project_task| %>
                <div class="card border-info mb-3 mt-3">
                    <div class="card-body">
                        <h3><%= link_to project_task.name, user_project_project_task_path(@user, @project, project_task)%></h3>
                        <p>Description:<br> <%= project_task.description %></p>
                        <strong>Due:<br><%= project_task.due_date %></strong><br>
                        <%= link_to 'Back to Project', user_project_path(@user, @project), class: 'btn btn-primary'  %>
                    </div>
                </div>
            <% end %>
    </div>
<% end %>

app/views/project_tasks/new.html.erb
<% content_for :header do %>
  <h1>Create a Project Task </h1>
<% end %>


<% content_for :content do %>
    <% if @project_task.errors.any? %>
  <ul>
      <% @project_task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
  </ul>
<% end %>
    <%= form_for [@user, @project, @project_task], url: { action: "create" }  do |form| %>
        <%= render partial: "form", locals: { f: form } %>
    <% end %>
<% end %>

app/views/project_tasks/recent.html.erb
<% content_for :header do %>
  <h1>Most Recent Project Tasks:</h1>
<% end %>

<% content_for :content do %>
    <% if @recent.any? %>
        <ol>
            <% @recent.each do |r| %>
                <li>
                    <strong>Name:</strong> <%= r.name %><br>
                    <strong>Description:</strong> <%= r.description %><br>
                    <strong>Created:</strong> <%= r.created_at.to_date %>
                </li>
            <% end %>
        </ol>
    <% else %>
        <h1>No Recent Tasks</h1>
    <% end %>

    <%= link_to 'Back', :back%>
<% end %>

app/views/project_tasks/show.html.erb
<% content_for :header do %>
  <div class="form-group mt-2 text-center">
    <h1><%= @project_task.name %></h1>
    <p><em>Description:<br><%= @project_task.description %></em></p>
    <p><em>Due:<br><%= @project_task.due_date %></em></p>
    <p><em>Done: <%= check_box_tag(@project_task.done?) %></em></p>
  </div>
<% end %>

<% content_for :content do %>
  <div class="form-group mt-2 text-center">
    <%= link_to 'Edit Project Task', edit_user_project_project_task_path(@user, @project, @project_task), class: 'btn btn-primary' %>
    <%= link_to 'Delete Project Task', user_project_project_task_path(@user, @project, @project_task), method: :delete, class: 'btn btn-primary' %>
    <%= link_to 'Back', :back, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/project_tasks/user_project_tasks.html.erb
<h1>Hi!</h1>

<% @project_tasks.each do |pt| %>

    <%= pt.name %>
<% end %>