config/routes.rb
Rails.application.routes.draw do

  # Homepage
  root 'welcome#home'

  # Devise
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # Nested Resources - users/projects
  resources :users, only: [:show] do
    resources :projects do
      resources :project_tasks
    end
  end

  # Task
  resources :tasks

  # Scope
  get '/project_tasks/recent', to: 'project_tasks#recent'

  get '/users/:id/project_tasks', to: 'project_tasks#user_project_tasks', as: :user_project_tasks

end

app/views/shared/_alerts.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
        <%= value %>
    </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-menu navbar-dark bg-dark">
      <div class="container">
        <div class="navbar-header navbar-dark">
          <h1><strong><%= link_to 'DevHub', root_path, class: 'navbar-brand mt-1' %></strong></h1>
        </div>
        <% if user_signed_in? %>
              <%= link_to 'Projects', user_projects_path(current_user) %>
          <% end %>
        <div id="navbar">

          <ul class="nav navbar-nav pull-right">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                  <%= current_user.email %><%= " (Admin)" if current_user.admin? == true %>
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to 'Profile', edit_user_registration_path %></li>
                  <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <div class='form-group mb-1'>
                <%= link_to 'Log In', new_user_session_path, class: 'btn btn-primary' %>
                <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary' %>
              </div>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>