config/routes.rb
Rails.application.routes.draw do

  # Homepage
  root 'welcome#home'

  # Devise
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # Nested Resources - users/projects
  resources :users, only: [:show] do
    resources :projects do
      resources :project_tasks
    end
  end

  # Task
  resources :tasks

  # Scope
  get '/project_tasks/recent', to: 'project_tasks#recent'

  get '/users/:id/project_tasks', to: 'project_tasks#user_project_tasks', as: :user_project_tasks

end

app/models/project.rb
class Project < ApplicationRecord
  # Associations
  belongs_to :user
  has_many :project_tasks, dependent: :destroy
  # has_many :users, through: :project_tasks
  has_many :tasks, through: :project_tasks
  # Validations
  validates :name, :due_date, presence: true


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # Helpers
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  def index
    @projects = Project.all
    @user = current_user
  end

  def new
    @project = Project.new
    @user = current_user
  end

  def create

    @project = Project.new(project_params)
    @user = current_user

    if @project.save
      redirect_to user_project_path(@user, @project), notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @project.update(project_params)
       redirect_to user_project_path(@user, @project), notice: 'Project was successfully updated.'
    else
       render :edit
    end
  end

  def destroy
    @user = current_user
    @project.destroy
    redirect_to user_projects_path(@user), notice: 'Project was successfully destroyed.'
  end

  private # This encapsulates these methods

  # Strong params
    def set_project
      @project = Project.find_by(id: params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :description, :due_date, :id, :user_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
    <div class = "container">
    <%= f.hidden_field :user_id, :value => @user.id %>
    <%= f.hidden_field :project_id, :value => @project.id %>
    <strong><%= f.label :name %></strong>
    <%= f.text_field :name, class:"form-control" %><br>
    <strong><%= f.label :description %></strong>
    <%= f.text_area :description, class:"form-control" %><br>
    <strong><%= f.label :due_date %></strong>
    <%= f.date_field :due_date, class:"form-control" %><br>
    </div>
    <%= f.submit 'Submit', class: "btn btn-primary" %>

app/views/projects/edit.html.erb
<% content_for :header do %>
  <h1>Edit Project </h1>
<% end %>

<% content_for :content do %>
  <%= form_for [@user, @project] do |form| %>
    <%= render partial: "form", locals: {f: form} %>
  <% end %>
<% end %>

app/views/projects/index.html.erb
<% content_for :header do %>
    <div class="text-center">
        <h1>Projects:</h1>
    </div>
<% end %>

<% content_for :content do %>
    <div class="text-center">
        <% @projects.each do |project| unless @projects.nil? %>
            <div class="card border-info mb-3">
                <div class="card-body">
                    Name:<h5 class="card-title"><%= link_to project.name, user_project_path(@user, project) %></h5>
                    Description:<p class="card-text"><%= project.description %><p>
                    Due Date:<h5 class="card-text"><%= project.due_date %></h5>
                    <%= link_to 'Create Task', new_user_project_project_task_path(@user, project), class: "btn btn-primary"  %>
                </div>
            </div>
        <% end %>
    <% end %>
    <br>
    <br>
    <p><%= link_to "Create New Project", new_user_project_path(@user), class: "btn btn-primary" %></p>
    </div>
<% end %>

app/views/projects/new.html.erb
<% content_for :header do %>
  <h1>Create a Project </h1>
<% end %>

<% content_for :content do %>
    <% if @project.errors.any? %>
    <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
    </ul>
  <% end %>

  <%= form_for [@user, @project] do |form| %>
    <%= render partial: "form", locals: {f: form} %>
  <% end %>
<% end %>

app/views/projects/show.html.erb
<% content_for :header do %>
    <div class="text-center">
        <h1><%= link_to @project.name, user_project_path(@user, @project) %></h1>
        <p>Description: <%= @project.description %></p>
        <strong>Due:<%= @project.due_date %></strong>
    </div>

    <div class="text-center mt-4">
            <%= link_to 'Add New Task', new_user_project_project_task_path(@user, @project), class: 'btn btn-primary' %>
    </div>

<% content_for :content do %>
    <% @project.project_tasks.each do |pt| %>
        <div class="card border-info mb-3">
            <div class="card-body text-center">
                <h3><%= link_to pt.name,  user_project_project_task_path(@user, @project, pt)%></h3>
                Description: <strong><%= pt.description %></strong><br>
                Due Date: <strong><%= pt.due_date %></strong><br>
                Done: <%= check_box_tag pt.done? %><br>
                <%= link_to 'Delete Task', user_project_project_task_path(@user, @project, pt), method: :delete, class: 'btn btn-primary' %>
            </div>
        </div>
        <% end %>
    <% end %>
    <% end %>
        <div class="form-group mt-2 text-center">
            <%= link_to 'Edit Project', edit_user_project_path(@user, @project), class: 'btn btn-primary' %>
            <%= link_to 'Delete Project', user_project_path(@user, @project), method: :delete , class: 'btn btn-primary'%>
            <%= link_to 'Back', :back , class: 'btn btn-primary'%>
        </div>